mysql:
  image: mysql:5.7.28
  volumes:
    - ./docker/mysql/conf:/etc/mysql/conf.d
    - ./docker/mysql/init:/docker-entrypoint-initdb.d
  environment:
    - MYSQL_ROOT_PASSWORD=3426
    - MYSQL_DATABASE=at
    - MYSQL_USER=at
    - MYSQL_PASSWORD=at
  ports:
    - "3306:3306"
nacos:
  image: nacos/nacos-server:1.1.4
  environment:
    - MODE=standalone
  ports:
    - "8848:8848"
storage:
  image: propersoft/docker-jre:8u171-jre
  volumes:
    - ./modules/storage/build/libs/storage-0.0.1-SNAPSHOT.jar:/usr/local/demo/storage.jar
  working_dir: /usr/local/demo
  links:
    - mysql
    - nacos
  command: java -jar /usr/local/demo/storage.jar
  ports:
    - "8081:8081"
account:
  image: propersoft/docker-jre:8u171-jre
  volumes:
    - ./modules/account/build/libs/account-0.0.1-SNAPSHOT.jar:/usr/local/demo/account.jar
  working_dir: /usr/local/demo
  links:
    - mysql
    - nacos
  command: java -jar /usr/local/demo/account.jar
  ports:
    - "8082:8082"
order:
  image: propersoft/docker-jre:8u171-jre
  volumes:
    - ./modules/order/build/libs/order-0.0.1-SNAPSHOT.jar:/usr/local/demo/order.jar
  working_dir: /usr/local/demo
  links:
    - mysql
    - nacos
  command: java -jar /usr/local/demo/order.jar
  ports:
    - "8083:8083"
business:
  image: propersoft/docker-jre:8u171-jre
  volumes:
    - ./modules/business/build/libs/business-0.0.1-SNAPSHOT.jar:/usr/local/demo/business.jar
  working_dir: /usr/local/demo
  links:
    - mysql
    - nacos
  command: java -jar /usr/local/demo/business.jar
  ports:
    - "8084:8084"
seata-server:
  image: seataio/seata-server:1.0.0
  volumes:
    - ./docker/seata/registry.conf:/seata-server/resources/registry.conf
  ports:
    - "8091:8091"