mysql:
  image: mysql:5.7.28
  volumes:
    - ./docker/mysql/conf:/etc/mysql/conf.d
  environment:
    - MYSQL_ROOT_PASSWORD=3426
    - MYSQL_DATABASE=ah
    - MYSQL_USER=ah
    - MYSQL_PASSWORD=ah
  ports:
    - "3306:3306"
nacos:
  image: nacos/nacos-server:1.1.4
  environment:
    - MODE=standalone
  ports:
    - "8848:8848"
storage:
  image: propersoft/docker-jre:8u171-jre
  volumes:
    - ./modules/storage/build/libs/storage-0.0.1-SNAPSHOT.jar:/usr/local/demo/storage.jar
  working_dir: /usr/local/demo
  links:
    - mysql
    - nacos
  command: java -jar /usr/local/demo/storage.jar
