spring:
  cloud:
    nacos:
      discovery:
        server-addr: nacos:8848
  datasource:
    url: jdbc:mysql://mysql:3306/at
    username: at
    password: at
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQL57Dialect

ribbon:
  eager-load:
    enabled: true
    clients: order, storage
feign:
  client:
    config:
      default:
        connectTimeout: 50000
        readTimeout: 50000